languageCode = "ja"
title = "WEBA"
author = "Akira HIRATA"
copyright = "© weba 2017"
baseURL = "http://hirata.blog"
publishDir = "docs"
hasCJKLanguage = true
disableHugoGeneratorInject = true

[Params]
# 独自変数
description = "Web・UXデザインやフロントエンド技術についてのブログです。"
analytics = "UA-01234567-8"
github = "gituhubアカウント名"
facebook = "http://fb.me/hirata.blog"
linkedin = "Linkedinアカウント名"

[permalinks]
post = "/:year-:month/:slug/"
