languageCode = "ja"
title = "WEBA"
author = "Akira HIRATA"
copyright = "© weba 2017"
baseURL = "https://hirata.blog"
publishDir = "docs"
hasCJKLanguage = true

[Params]
# 独自変数
description = "Web・UXデザインやフロントエンド技術についてのブログです。"
analytics = "UA-01234567-8"
github = "psephopaiktes"
facebook = "https://fb.me/hirata.blog"

[permalinks]
post = "/:filename/"
